version: "3.8"

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: ./
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    env_file:
      - .env

volumes:
  db:
